apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  labels: {{ include "common.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.username  | b64enc | quote }}
  password: {{ .Values.password  | b64enc | quote }}

